#Minecraft server properties
#Sun Feb 08 20:34:01 ICT 2026
allow-flight=true
allow-nether=true
difficulty=1
level-name=world
level-seed=
max-players=20
online-mode=false
pvp=true
server-ip=
server-port=25565
spawn-animals=true
spawn-monsters=true
spawn-protection=16
view-distance=8
white-list=false
